CREATE TABLE "blockId" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "blockId_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"workchain" integer NOT NULL,
	"network" text NOT NULL,
	"shard" bigint,
	"seqno" bigint NOT NULL,
	"rootHash" varchar(128) NOT NULL,
	"fileHash" varchar(128) NOT NULL,
	CONSTRAINT "blockId_seqno_unique" UNIQUE("seqno"),
	CONSTRAINT "blockId_rootHash_unique" UNIQUE("rootHash"),
	CONSTRAINT "blockId_fileHash_unique" UNIQUE("fileHash")
);
--> statement-breakpoint
CREATE TABLE "deposits_tx" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "deposits_tx_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"hash" varchar(128) NOT NULL,
	"amount" bigint NOT NULL,
	"lt" bigint NOT NULL,
	"from" varchar(128) NOT NULL,
	"to" varchar(128) NOT NULL,
	"memo" varchar(256),
	"now" date NOT NULL,
	"status" text NOT NULL,
	"network" text NOT NULL,
	"seqno" bigint NOT NULL,
	"workchain" integer NOT NULL,
	"shard" bigint,
	CONSTRAINT "deposits_tx_hash_unique" UNIQUE("hash"),
	CONSTRAINT "deposits_tx_from_lt" UNIQUE("from","lt")
);
--> statement-breakpoint
CREATE TABLE "downstream" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "downstream_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"downstreamSlug" varchar(32) NOT NULL,
	"status" text NOT NULL,
	"depositTxId" integer NOT NULL,
	"userId" varchar(64) NOT NULL,
	"from" varchar(128) NOT NULL,
	"hash" varchar(128) NOT NULL,
	"amount" bigint NOT NULL,
	"txStatus" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "downstream" ADD CONSTRAINT "depositTx_fk" FOREIGN KEY ("depositTxId") REFERENCES "public"."deposits_tx"("id") ON DELETE no action ON UPDATE no action;